# ARRAY

In [2]:
import array
arr=array.array('i',[1,2,3,4])
arr

array('i', [1, 2, 3, 4])

In [3]:
arr.buffer_info()

(2092495663056, 4)

In [5]:
arr.typecode

'i'

In [6]:
from array import *

arr2=array('f',[3,6,9])
arr2

array('f', [3.0, 6.0, 9.0])

In [24]:
import numpy as np

a1=np.array([1,2,3],int)

In [25]:
a1

array([1, 2, 3])

In [26]:
a1.dtype

dtype('int32')

In [33]:
a=np.zeros(4)

In [31]:
a

array([0., 0., 0., 0.])

In [36]:
a2=np.ones(4,int)
a2

array([1, 1, 1, 1])

In [42]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])

print(np.concatenate([ar1,ar2]))

[1 2 3 4 5 6]


In [43]:
print(id(ar1))
print(id(ar2))

2092751724048
2092751723472


In [45]:
ar3=ar1.view()
print(id(ar3))

2092751724240


In [46]:
ar1=np.array([1,2,3])
ar1[1]=9

In [47]:
from numpy import *
w=array([1,23,4])
w

array([ 1, 23,  4])